module: AlamofireSync

author: Gumob
author_url: http://gumob.com
github_url: https://github.com/gumob/AlamofireSync
copyright: 'Copyright © 2020 Gumob. All rights reserved.'

readme: "README.md"
# documentation: "USAGE.md"

theme: fullwidth
# theme: "themes/fullwidth-ex"

xcodebuild_arguments:
  - -project
  - ../AlamofireSync.xcodeproj
  - -scheme
  - AlamofireSync-macOS

output: "docs"
min_acl: public
clean: true
skip_undocumented: false
hide_documentation_coverage: true
source_directory: Source
umbrella_header: "Source/AlamofireSync.h"

exclude:
  - Example/*
  - Tests/*
  - UITests/*

# custom_categories:

#   - name: Core
#     children:
#     - AlamofireSync