language: objective-c
os: osx
osx_image: xcode11.5

branches:
  only:
    - master
    - develop
#    - "/^v?[0-9\\.]+/"

cache:
  bundler: true
  cocoapods: true
  directories:
    - Carthage

env:
  global:
    - XCODE_PROJECT="AlamofireSync.xcodeproj"
    - IOS_SCHEME="AlamofireSync-iOS"
    - MACOS_SCHEME="AlamofireSync-macOS"
    - TVOS_SCHEME="AlamofireSync-tvOS"

matrix:
  include:
    # iOS Tests
    - env: XCODE_TEST="YES" SCHEME="$IOS_SCHEME"   DESTINATION="OS=13.5,name=iPhone 11 Pro" COVERAGE="YES" CODECOV_FLAG="ios13"
    - env: XCODE_TEST="YES" SCHEME="$IOS_SCHEME"   DESTINATION="OS=12.4,name=iPhone X"      COVERAGE="NO"  CODECOV_FLAG="ios12"
    - env: XCODE_TEST="YES" SCHEME="$IOS_SCHEME"   DESTINATION="OS=11.4,name=iPhone 7"      COVERAGE="NO"  CODECOV_FLAG="ios11"
    - env: XCODE_TEST="YES" SCHEME="$IOS_SCHEME"   DESTINATION="OS=10.3.1,name=iPhone 6"    COVERAGE="NO"  CODECOV_FLAG="ios10"
    # tvOS Tests
    - env: XCODE_TEST="YES" SCHEME="$TVOS_SCHEME"  DESTINATION="OS=13.4,name=Apple TV 4K"   COVERAGE="NO"  CODECOV_FLAG="tvos13"
    - env: XCODE_TEST="YES" SCHEME="$TVOS_SCHEME"  DESTINATION="OS=12.4,name=Apple TV 4K"   COVERAGE="NO"  CODECOV_FLAG="tvos12"
    - env: XCODE_TEST="YES" SCHEME="$TVOS_SCHEME"  DESTINATION="OS=11.4,name=Apple TV"      COVERAGE="NO"  CODECOV_FLAG="tvos11"
    # macOS Tests
    - env: XCODE_TEST="YES" SCHEME="$MACOS_SCHEME" DESTINATION="arch=x86_64"                COVERAGE="NO"  CODECOV_FLAG="macos"
    # Lint
    - env: CARTHAGE_TEST="YES"
    - env: SWIFT_LINT="YES"
    - env: POD_LINT="NO"

before_install:
  - if [ "$XCODE_TEST" == "YES" ]; then
    gem install xcpretty --no-document --quiet;
    fi
  - if [ "$CARTHAGE_TEST" = "YES" ] || [ "$XCODE_TEST" = "YES" ]; then
    brew update;
    brew outdated carthage || brew upgrade carthage;
    carthage bootstrap --cache-builds --verbose;
    fi
  - if [ "$POD_LINT" == "YES" ]; then
    gem install cocoapods --pre --no-document --quiet;
    pod repo update;
    fi

install:
  - if [ "$SWIFT_LINT" == "YES" ]; then
    ./install-swiftlint.sh;
    fi

script:
  - set -o pipefail;
  - swift -version;

  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    xcrun simctl list;
    xcodebuild -version;
    xcodebuild -showsdks;
    xcodebuild -list;
    fi

  - if [ "$XCODE_TEST" == "YES" ]; then
    xcodebuild clean test -project "$XCODE_PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -enableCodeCoverage $COVERAGE | xcpretty -c;
    fi

  - if [ "$CARTHAGE_TEST" == "YES" ]; then
    carthage build --no-skip-current --platform iOS;
    fi

  - if [ "$SWIFT_LINT" == "YES" ]; then
    swiftlint lint;
    fi

  - if [ "$POD_LINT" == "YES" ]; then
    pod lib lint;
    fi

after_success:
  - if [ "$COVERAGE" == "YES" ]; then
    bash <(curl -s https://codecov.io/bash) -J 'AlamofireSync' -cF "$CODECOV_FLAG";
    fi
